package com.fh.unittests.frameworktest;


import com.fh.core.TestLocalController;
import com.trigon.testbase.TestUtilities;
import org.openqa.selenium.By;
import org.testng.annotations.Test;

import static autogenerated.core.TestLocalController.tObj;


public class frameworkTest extends TestLocalController {

    @Test(enabled = false)
    public void unitTest() {
        TestUtilities.browser().findElement(By.id("twotabsearchtextbox")).sendKeys("iphone");
        author_ScenarioName("bhaskar_parallelClass1_Method1", "parallelClass1_Method1 scenario");
        testStatus("PASS", "parallelClass1_Method1 PASSED");
    }

    @Test
    public void testGoogleSearch() {
//        WebElement element = TestUtilities.browser().findElement(By.xpath("(//*[@type=\"text2\"])[1]"));
//        element.sendKeys("iPhone");
        //element.submit();
        //browser().findElement(By.linkText("Web")).click();
        tObj().frameworkTest().searchTextBox_enterText("bhaskar");
        author_ScenarioName("bhaskar_parallelClass1_Method2", "parallelClass1_Method2 scenario");
        testStatus("PASS", "parallelClass1_Method2 PASSED");

    }
}
