package com.fh.core;

import autogenerated.pages.web.fhapp.AppFrameworkTest;

public class AppFrameworkTestController extends TestLocalController {
    public static AppFrameworkTest tFHApp() {
        return new AppFrameworkTest();
    }
}