package com.fh.core;

import autogenerated.objrepo.Fhweb;
import com.trigon.wrapper.TestModels;

    public class FhwebController extends TestLocalController {
        public static Fhweb tFhweb() {
            return new Fhweb();
        }
}
