package com.fh.core;

import autogenerated.objrepo.Fhweb;
import autogenerated.pages.web.fhweb.FrameworkTest;

public class FrameworkTestController extends TestLocalController {
    public static FrameworkTest tFH() {
        return new FrameworkTest();
    }
}