/////////////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by CODE GENERATOR.
// DO NOT MODIFY THIS FILE! All your modifications will be lost!
// Modify all your changes in your respective JSON Files only.
// You can regenerate this file by executing GenerateCode.xml
// You DON'T need to regenerate code if there is change in Locators.
// You must regenerate code, When ever you add new element or modify/add actionevent.
//
// Contact bhaskar.marrikunta@foodhub.com for any issues.
//
/////////////////////////////////////////////////////////////////////////////////////