package com.trigon.tribot;


import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;
import org.testng.annotations.Test;

import java.io.File;

import static com.trigon.utils.CommonUtils.fileOrFolderDelete;

public class CleanTriBot {
    private static final Logger logger = LogManager.getLogger(CleanTriBot.class);


    @Test
    private void removeGeneratedFiles() {
        logger.info("Removing Generated Files...");
        fileOrFolderDelete(new File("src/test/java/autogenerated/"));
    }

}
