package com.fh.adhoc;

import autogenerated.core.TestModels;
import com.fh.core.TestLocalController;
import org.openqa.selenium.WebElement;
import org.testng.annotations.Test;

import java.util.List;

public class Yell extends TestLocalController {

    @Test
    public void yellData() {
        author_ScenarioName("Bhaskar", "Yell");
        addHeaderToCustomReport("S.No", "SearchURL", "Source", "businessType","businessName", "businessURL","services", "businessWebsite", "businessPhone", "businessAddress", "businessHours","ratings","reviews");
        TestModels model = new TestModels();
        String businessType = "Car Wash";

        String searchURL = "https://www.yell.com/ucs/UcsSearchAction.do?scrambleSeed=634404639&keywords=car+wash&location=AA11AA";
        model.navigateToUrl(searchURL);

        List<WebElement> listOfElements = model.findElements("css=div[class='row businessCapsule--mainRow']");
        model.click("css=button[id=\"CookiePolicyClose\"]", "wait_0", "isPresent");
        //(//div[@class='row businessCapsule--mainRow'])[1]//div[contains(@class,'businessCapsule--titSpons')]

        if (listOfElements.size() > 0) {
            for (int i = 1; i <= listOfElements.size(); i++) {
                String businessName = model.getText("xpath=(//div[@class='row businessCapsule--mainRow'])[" + i + "]//a[contains(@class,'businessCapsule--title')]", "wait_0", "isPresent");
                String services = model.getText("xpath=(//div[@class='row businessCapsule--mainRow'])[" + i + "]//div[contains(@class,'businessCapsule--classStrap')]", "wait_0", "isPresent");

                String businessURL = model.getAttribute("xpath=(//div[@class='row businessCapsule--mainRow'])[" + i + "]//a[contains(@class,'businessCapsule--title')]", "href", "wait_0", "isPresent");
                String businessWebsite = model.getAttribute("xpath = ((//div[@class='row businessCapsule--mainRow'])[" + i + "]//div[contains(@class,'businessCapsule--ctas')]/a)[2]", "href", "wait_0", "isPresent");
                model.click("xpath=(//div[@class='row businessCapsule--mainRow'])[" + i + "]//div[contains(@class,'businessCapsule--ctaItem')]", "wait_0", "isPresent");
                String businessPhone = model.getText("xpath=(//div[@class='row businessCapsule--mainRow'])[" + i + "]//div[contains(@class,'business--telephone')]//span[contains(@class,'business--telephoneNumber')]", "wait_0", "isPresent");
                String businessAddress = model.getText("xpath=(//div[@class='row businessCapsule--mainRow'])[" + i + "]//span[@itemprop='address']", "wait_0", "isPresent");
                String businessHours = model.getText("xpath=(//div[@class='row businessCapsule--mainRow'])[" + i + "]//div[contains(@class,'businessCapsule--openingHours') ]", "wait_0", "isPresent");

                String ratings = model.getText("xpath=(//div[@class='row businessCapsule--mainRow'])[" + i + "]//span[contains(@class,'starRating--average')]", "wait_0", "isPresent");
                String reviews = model.getText("xpath=(//div[@class='row businessCapsule--mainRow'])[" + i + "]//span[contains(@class,'starRating--total')]", "wait_0", "isPresent");
                addRowToCustomReport(String.valueOf(i), searchURL, "PDQ",businessType,businessName, businessURL,services, businessWebsite, businessPhone, businessAddress,businessHours,ratings,reviews);
            }

        }


    }
}
